os:
    - linux

env:
    - BOOST_LIBRARIES=any,lexical_cast,variant,type_index,core

before_install:
    - echo OS is ${TRAVIS_OS_NAME}
    - wget https://raw.githubusercontent.com/boostorg/boost/develop/tools/regression/src/run.py

script:
    - python run.py --runner=indirect_travisci_tests --toolsets=gcc --tag=master --libraries=${BOOST_LIBRARIES}

after_success:
    - mkdir cover
    - find ./ -name "*.gcda" -exec cp "{}" ../cover \;
    - find ./ -name "*.gcno" -exec cp "{}" ../cover \;
    - sudo apt-get install -qq python-yaml lcov
    - lcov --directory ../cover --base-directory ../cover --capture --output-file ../cover/coverage.info
    - lcov --remove ../cover/coverage.info '/usr*' -o ../cover/coverage.info
    - gem install coveralls-lcov
    - coveralls-lcov ../cover/coverage.info
