#    - NAME=CI-p-1 BOOST_LIBRARIES=--libraries=numeric,parameter
#    - NAME=CI-p-2 BOOST_LIBRARIES=--libraries=gil,graph,graph_parallel,heap,icl,integer,move,optional,lexical_cast,pool,lambda,tokenizer,tuple,program_options,qvm,process,mp11,metaparse,polygon,predef,preprocessor,mpl,mpi,bcp,poly_collection,interprocess
#    - NAME=CI-p-3 BOOST_LIBRARIES=--libraries=beast,stacktrace,msm,lockfree,spirit
#    - NAME=CI-p-4 BOOST_LIBRARIES=--libraries=io,iostreams,locale,local_function,thread,logic,multi_index
#    - NAME=CI-p-5 BOOST_LIBRARIES=--libraries=fiber,hana,phoenix
#    - NAME=CI-p-6 BOOST_LIBRARIES=--libraries=accumulators,algorithm,align,any,application,array,asio,assert,assign,atomic,bimap,bind,chrono,circular_buffer,compatibility,compute,concept_check,config,container,context,conversion,convert,core,coroutine,coroutine2,crc,date_time,detail,disjoint_sets,dll,document,dynamic_bitset,endian,exception,filesystem,flyweight,foreach,format,function,functional,function_types,fusion
#    - NAME=CI-p-7 BOOST_LIBRARIES=--libraries=type_index,typeof,type_traits,units,unordered,utility,uuid,variant,vmd,wave,winapi,xpressive,static_assert,sort,timer,smart_ptr,type_erasure,random,iterator
#    - NAME=CI-p-8 BOOST_LIBRARIES=--libraries=signals,signals2,statechart,sync,system,test,throw_exception,tr1,trie,tti,intrusive,multi_array,log
#    - NAME=CI-p-9 BOOST_LIBRARIES=--libraries=property_map,property_tree,proto,ptr_container,python,range,ratio,rational,regex,scope_exit,serialization

build: off

environment:
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma2 -mx=3
  matrix:
  
  - NAME: CI-p-1 
    BOOST_LIBRARIES: --libraries=numeric,parameter
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - NAME: CI-p-2 
    BOOST_LIBRARIES: --libraries=gil,graph,graph_parallel,heap,icl,integer,move,optional,lexical_cast,pool,lambda,tokenizer,tuple,program_options,qvm,process,mp11,metaparse,polygon,predef,preprocessor,mpl,mpi,bcp,poly_collection,interprocess
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - NAME: CI-p-3 
    BOOST_LIBRARIES: --libraries=beast,stacktrace,msm,lockfree,spirit
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - NAME: CI-p-4 
    BOOST_LIBRARIES: --libraries=io,iostreams,locale,local_function,thread,logic,multi_index
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - NAME: CI-p-5 
    BOOST_LIBRARIES: --libraries=fiber,hana,phoenix
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - NAME: CI-p-6 
    BOOST_LIBRARIES: --libraries=accumulators,algorithm,align,any,application,array,asio,assert,assign,atomic,bimap,bind,chrono,circular_buffer,compatibility,compute,concept_check,config,container,context,conversion,convert,core,coroutine,coroutine2,crc,date_time,detail,disjoint_sets,dll,document,dynamic_bitset,endian,exception,filesystem,flyweight,foreach,format,function,functional,function_types,fusion
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - NAME: CI-p-7 
    BOOST_LIBRARIES: --libraries=type_index,typeof,type_traits,units,unordered,utility,uuid,variant,vmd,wave,winapi,xpressive,static_assert,sort,timer,smart_ptr,type_erasure,random,iterator
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015  
  - NAME: CI-p-8
    BOOST_LIBRARIES: --libraries=signals,signals2,statechart,sync,system,test,throw_exception,tr1,trie,tti,intrusive,multi_array,log
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015  
  - NAME: CI-p-9
    BOOST_LIBRARIES: --libraries=property_map,property_tree,proto,ptr_container,python,range,ratio,rational,regex,scope_exit,serialization
    TOOLSET: vs-2008
    platform: 32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015  
    
    
    
    
  
  
  
#  - TOOLSET: vs-2008
#    platform: 32
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: vs-2010
#    platform: 32
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: vs-2012
#    platform: 32
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: vs-2013
#    platform: 32
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: vs-2013
#    platform: 64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: vs-2015
#    platform: 32
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: vs-2015
#    platform: 64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: vs-2017
#    platform: 32
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#  - TOOLSET: vs-2017
#    platform: 64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#  - TOOLSET: vs-2017
#    CXXFLAGS: /std:c++14
#    platform: 64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#  - TOOLSET: vs-2017
#    CXXFLAGS: /std:c++latest
#    platform: 64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#  - TOOLSET: mingw-5
#    platform: 32
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#  - TOOLSET: mingw64-6
#    platform: 64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

init:
    - cd %APPVEYOR_BUILD_FOLDER%
    - appveyor DownloadFile "https://raw.githubusercontent.com/boostorg/regression/develop/ci/src/ci_boost_common.py"
    - appveyor DownloadFile "https://raw.githubusercontent.com/boostorg/regression/develop/ci/src/ci_boost_library_test.py"
    - appveyor DownloadFile "https://raw.githubusercontent.com/boostorg/regression/develop/testing/src/run.py"
    - cd %APPVEYOR_BUILD_FOLDER%

install: python ci_boost_library_test.py install
    
test_script:
#    - if [ "${CXXFLAGS}" != "" ] ; then python run.py --runner=${NAME}-${TOOLSET}-${CXXFLAGS} --bjam-options="-j2 cxxflags=${CXXFLAGS}" --toolsets=${TOOLSET} --tag=develop ${BOOST_LIBRARIES} ; fi
    - python run.py --runner=%NAME%-%TOOLSET%-%platform% --bjam-options=-j2 --toolsets=%TOOLSET% --tag=develop %BOOST_LIBRARIES%
